name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build:packages

      - name: Lint cdn
        run: yarn lint:cdn

      - name: Build cdn
        run: yarn build:cdn

      - name: Test packaging
        run: yarn workspace @standardnotes/community-cdn run package
